### ISSUE TITLE
Review my update PR for nsone provider

### ISSUE THREAD

**Issue by josephholsten** [ns1/ns1-go#19]
I'm in the middle of updating Ensighten/terraform's nsone provider branch to use v2. Feel free to chime in if I do anything dumb: https://github.com/Ensighten/terraform/pull/30

**Comment by pashap** [comment]
👍 will review

**Comment by josephholsten** [comment]
@pashap alright, I've got it compiling. Haven't attempted to make run the integration tests yet, but this should be close to the ultimate structure. In particular, I'll want feedback on the `data.Meta` serialization in `resource_record.go`

**Comment by pashap** [comment]
@josephholsten sorry for delay, i am looking through the PR now. i tried getting v2 and terraform going locally, but didnt have enough time to really dig into terraform.

**Comment by josephholsten** [comment]
yow, there is a bunch of error handling required to get these structured `data.Meta`s working correctly. Fortunately, this is all error handling that couldn't even be performed with the old data structures, so we're getting benefit from it.

**Comment by josephholsten** [comment]
@pashap ok, I've updated the PR to fully pass tests, and made them a bit more thorough.

**Comment by pashap** [comment]
@josephholsten thank you for sticking with, sorry for delay again. ironically, i just created a temp [terraform-provider-ns1](https://github.com/ns1/terraform-provider-ns1) repo in the `ns1` organization. i started working on what you updated from @bobtfish and @sarguru. i can create an issue in the temp repo with some of the changes i made, and whether the changes are worth keeping. otherwise, i am looking over your PR now. and from the quick looks of it, im liking a lot of what you did vs what i did with metadata

**Comment by pashap** [comment]
^ I mainly just wanted one place to communicate and easily push to

**Comment by josephholsten** [comment]
I've created a version of the above PR which is rebased onto terraform master. See https://github.com/hashicorp/terraform/pull/10172

**Comment by josephholsten** [comment]
I've created a version of the above PR which is rebased onto terraform master. See https://github.com/hashicorp/terraform/pull/10172

**Comment by pashap** [comment]
thanks man, im looking over yours now. i love the name of your feature branch in that PR haha :)
