### ISSUE TITLE
Failure unmarshalling CAA record

### ISSUE THREAD

**Issue by siwyd** [ns1/ns1-go#38]
I'm running into an issue unmarshalling a CAA record for my domain. I think the interface is expecting an array of all strings in the JSON response, but the response has an array of mixed types, the first being an integer and followed by strings.

This is the script used:
```
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	api "gopkg.in/ns1/ns1-go.v2/rest"
)

func main() {
	k := os.Getenv("NS1_APIKEY")
	if k == "" {
		fmt.Println("NS1_APIKEY environment variable is not set, giving up")
		os.Exit(1)
	}

	httpClient := &http.Client{Timeout: time.Second * 10}
	doer := api.Decorate(httpClient, api.Logging(log.New(os.Stdout, "", log.LstdFlags)))
	client := api.NewClient(doer, api.SetAPIKey(k))

	records, _, err := client.Records.Get("siwyd.com", "siwyd.com", "CAA")
	if err != nil {
		log.Fatal(err)
	}

	for _, a := range records.Answers {
		fmt.Println(a)
	}

}
```

Output:
```
2017/09/26 13:38:13 go-ns1/2.0.0: GET https://api.nsone.net/v1/zones/siwyd.com/siwyd.com/CAA
2017/09/26 13:38:14 json: cannot unmarshal number into Go struct field Answer.answer of type string
exit status 1
```

If I change "CAA" to "MX", I get the proper output:
```
2017/09/26 13:37:56 go-ns1/2.0.0: GET https://api.nsone.net/v1/zones/siwyd.com/siwyd.com/MX
10 mxb.mailgun.org
10 mxa.mailgun.org
```

This is the actual JSON response with curl (notice the integer in the answer array):
```
{
  "domain": "siwyd.com",
  "zone": "siwyd.com",
  "use_client_subnet": true,
  "answers": [
    {
      "answer": [
        0,
        "issuewild",
        ";"
      ],
      "meta": {},
      "id": "59a6e940c9c79d000120d3e3"
    },
    {
      "answer": [
        0,
        "issue",
        "letsencrypt.org"
      ],
      "meta": {},
      "id": "59a6e940c9c79d000120d3e4"
    }
  ],
  "id": "59a6e940c9c79d000120d3e5",
  "regions": {},
  "meta": {},
  "link": null,
  "filters": [],
  "ttl": 3600,
  "tier": 1,
  "type": "CAA",
  "networks": [
    0
  ]
}
```

This is the response for an MX record:
```
{
  "domain": "siwyd.com",
  "zone": "siwyd.com",
  "use_client_subnet": true,
  "answers": [
    {
      "answer": [
        "10",
        "mxb.mailgun.org"
      ],
      "meta": {},
      "id": "59bec368a632f6000161d493"
    },
    {
      "answer": [
        "10",
        "mxa.mailgun.org"
      ],
      "meta": {},
      "id": "59bec368a632f6000161d494"
    }
  ],
  "id": "59517182a632f6000189affa",
  "regions": {},
  "meta": {},
  "link": null,
  "filters": [],
  "ttl": 14400,
  "tier": 1,
  "type": "MX",
  "networks": [
    0
  ]
}
```

**Comment by stuffcarlcodes** [comment]
Apologies for the delayed response. We are currently reviewing this issue internally and will address it in the near term.

UPDATE: I've submitted a feature request to get the CAA record JSON blob to respond properly across the API based on the issue initially described. As soon as we've made the global change, we will let you know! Thanks for keeping us apprised of issues :)

**Comment by siwyd** [comment]
Thanks!

**Comment by mburtless** [comment]
Hi @siwyd - I've just joined NS1 and will be helping to maintain the repo moving forward.

I know it's been awhile since you originally created this issue, but I just wanted to comment here to confirm that the issue is still reproducible and that I'll be re-raising this issue with our API team.

Apologies for the delay and thanks for your patience.

**Comment by mburtless** [comment]
As you've correctly pointed out, the underlying issue here is that the API can return values for answers that are either String or Int, but the struct used in the SDK expects all values to be Strings.

However, this is true for more than just CAA records.  MX records can return Ints as well, if an Int is passed in the JSON body when the record is created.  The difference is that CAA records will _only_ return Ints, regardless of the type used to create them.

To resolve this we'll need to introduce some type of polymorphism in the model for Answers (i.e. using empty interface) or use a custom JSON demarshaler.  Will take some investigation to figure out which introduces the least amount of breaking change.

**Comment by ChrisMcKee** [comment]
@mburtless https://github.com/ns1/ns1-go/pull/73 interface seemed to work fine as theres nothing really manipulating the data in any of these libs; its just building json and firing it at the api.
